name: qrmenu
description: QR Restaurant Menu Web App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  go_router: ^10.0.0
  dio: ^5.3.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: ViaodaLibre
      fonts:
        - asset: assets/fonts/ViaodaLibre-Regular.ttf